### ISSUE TITLE
add Controllers, DTO

### ISSUE THREAD

**Issue by hotabsc** [Olegoy/ProjectManager#1]

**Comment by hotabsc** [comment]
1. ProjectController 
не хватает URI для самого контроллера

2. расширенный импорт лучше не использовать, т к могут возникнуть коллизии с одинаковыми имена файлов

3. Release*Dto 
а для объекта Релиз идентификатор это сама версия? Почему в dto нет дат?)

**Comment by hotabsc** [comment]
остальное все, после исправлений в отдельной bugfix-ветке можно мержить

**Comment by Olegoy** [comment]
>2 расширенный импорт лучше не использовать, т к могут возникнуть коллизии с одинаковыми имена файлов 
 
прописал отдельные импорты.

>3 Release*Dto
>а для объекта Релиз идентификатор это сама версия? Почему в dto нет дат?

даты и id добавил.

**Comment by Olegoy** [comment]
>ProjectController
не хватает URI для самого контроллера

добавил URI к контроллерам

**Comment by hotabsc** [comment]
2ое ДЗ - ок
